Shell script that runs a Python script

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -2,15 +2,15 @@
 
 # Check if the PYFILE environment variable is set
 if [ -z "$PYFILE" ]; then
-echo "Error: PYFILE environment variable is not set."
-exit 1
+	echo "Error: PYFILE environment variable is not set."
+	exit 1
 
 fi 
 
 # Check if the specified Python file exists
 if [ ! -f "$PYFILE" ]; then
-echo "Error: Python file '$PYFILE' not found."
-exit 1
+	echo "Error: Python file '$PYFILE' not found."
+	exit 1
 
 fi
 
